### ISSUE TITLE
Allow inspect multiple directories

### ISSUE THREAD

**Issue by JoniJnm** [shopsys/phpstorm-inspect#4]
The inspect.sh script allows inspect multiple directories: `-d /dirA -d /dirB`

**Comment by sustmi** [comment]
I am considering rewriting the main `phpstorm-inspect.php` script as a Symfony command because the current CLI is already a bit complex:
```
Expected 5 or 6 arguments:
vendor/bin/phpstorm-inspect <inspectShExecutableFilepath> <phpstormSystemPath> <projectPath> <inspectionProfileFilepath> <inspectedDirectory> [<format>, accepted values: "text" / "checkstyle"]
```
I cannot imagine specifying multiple `<inspectedDirectory>` right now.

But if we used Symfony's [Command](http://symfony.com/doc/current/console.html) component we could quite easily transform the `<format>` into an option and then have multiple directories as the last argument(s).

It will also make easier adding something like `--no-cache-clear` option that I suggested here: https://github.com/shopsys/phpstorm-inspect/issues/6 .

What do you think?

**Comment by JoniJnm** [comment]
Yes, the params must be rewrited. I forked your proyect and had to force format param to accept an array of dirs at the end.

* https://github.com/JoniJnm/phpstorm-inspect/blob/tmp/bin/phpstorm-inspect.php#L55

**Comment by JoniJnm** [comment]
https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000132670-inspect-sh-specify-scope
